In [4]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.13


# NumPy

https://numpy.org/

In [5]:
# Importando o NumPy
import numpy as np

In [6]:
np.__version__

'1.25.2'

# Criando Arrays NumPy

In [7]:
# Array criado a partir de uma lista Python
array = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [8]:
print(array)

[10 21 32 43 48 15 76 57 89]


In [9]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(array)

numpy.ndarray

In [10]:
# Verificando o formato do array
array.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPUs.

![DSA](imagens/formatos.png)

# Indexação em Arrays Numpy

In [11]:
print(array)

[10 21 32 43 48 15 76 57 89]


In [12]:
# Imprimindo um elemento específico no array
array[4]

48

In [13]:
# Indexação, o último índice é exclusivo
array[1:4]

array([21, 32, 43])

In [14]:
# Indexação 
array[1:4+1]

array([21, 32, 43, 48])

In [15]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [16]:
# Imprimindo os elementos dos índices
array[indices]

array([21, 32, 15, 76])

In [17]:
# Cria uma máscara booleana para os elementos pares
mask = (array % 2 == 0)

In [18]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [19]:
array[mask]

array([10, 32, 48, 76])

In [20]:
# Alterando um elemento do array
array[0] = 100

In [21]:
print(array)

[100  21  32  43  48  15  76  57  89]


In [22]:
# Não é possível incluir elemento de outro tipo 
try:
    array[0] = 'Novo Elemento'
except:
    print('Operação não permitida')

Operação não permitida


In [23]:
array[0] = 'Novo Elemento'

ValueError: invalid literal for int() with base 10: 'Novo Elemento'

# Funções NumPy

In [25]:
# A função array() cria um array NumPy
arr2 = np.array([1,2,3,4,5])

In [26]:
print(arr2)

[1 2 3 4 5]


In [27]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [29]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os métodos disponíveis em objetos NumPy
arr2

array([1, 2, 3, 4, 5])

In [30]:
# Usando o método cumsum (soma acumulada)
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [31]:
# cumprod (produto acumlado)
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [32]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os métodos disponíveis em objetos NumPy
np

<module 'numpy' from 'C:\\Users\\gabri\\anaconda3\\lib\\site-packages\\numpy\\__init__.py'>

In [39]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = np.arange(0, 100, 5)

In [40]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [41]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [42]:
# Formato do array
np.shape(arr3)

(20,)

In [43]:
print(arr3.dtype)

int32
